### Signup a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"session@gmail.com",
    "password": "!Pass4sure"
}

### Sign in a user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"session@gmail.com",
    "password": "!Pass4sure"
}


### Get the currentl;y signed in user

GET http://localhost:3000/auth/whoami

### Get the currentl;y signed in user

POST  http://localhost:3000/auth/signout


### Find a particular user with a given ID

GET http://localhost:3000/auth/2


### Find all users with a given EMAIL
GET http://localhost:3000/auth?email=aaa@gmail.com

### Delete the users with a given ID
DELETE  http://localhost:3000/auth/2

### Update a user
PATCH   http://localhost:3000/auth/2
Content-Type:  application/json

{
    "password": "aaa@mailcom"
}


### Set a color
GET  http://localhost:3000/auth/colors/green


### Get the color
GET  http://localhost:3000/auth/colors



